### ISSUE TITLE
slot attributes are deprecated - rename props for compatibility

### ISSUE THREAD

**Issue by dikiharifwibowo** [lcw3176/vue3-google-adsense#4]
When using vue3-google-adsense in a Vue 3 project, ESLint raises the following warning:

```
vue/no-deprecated-slot-attribute
slot attributes are deprecated.eslint-plugin-vue
```

The slot attribute is deprecated in Vue 3, and it should be replaced by the v-slot directive. Additionally, there are props such as slot and client which could benefit from renaming for better clarity and alignment with the deprecation fixes.

**Steps to reproduce:**

1. Install the vue3-google-adsense package in a Vue 3 project.
2. Use the component with the slot and client props.
3. Run ESLint or check the console for deprecation warnings.

**Proposed Solution:**

1. Change slot to slotId and client to clientId in the component props.
2. Update all relevant places in the documentation and codebase where slot and client are used to reflect the new names slotId and clientId.

**Comment by lcw3176** [comment]
Thank you for all your hard work and for contributing to the project. Wishing you nothing but happiness!
